version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: evertask
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: evertask_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: